### PR TITLE
Use try catch for atob()

### LINKED ISSUE #293: Unhandled error when issuing custom commands
Steps to reproduce:

1. Login to allmon3
2. Select execute custom command on a node
3. In the dropdown select "Custom Command" 
4. Enter any text that is **not** a real command like "banana" for example.

Error:
```
Uncaught (in promise) InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at sendCommand (commands.js?v=1.6.0:27:13)
```

### PR DESCRIPTION
**Pull request by Pross**
Fixes #293

### CODE REVIEW

**Review by mkmer — COMMENTED** [review]
Should we be doing something when it fails (in the catch)?  Not setting `res`? Or puting `res=` in the `try` and `Command Failed` in the error? (I'm not sure if it actually failed if the `atob()` failes.  We did get a success with what must be a malformed conversion?)

**Comment by Pross** [comment]
> Should we be doing something when it fails (in the catch)? Not setting `res`? Or puting `res=` in the `try` and `Command Failed` in the error? (I'm not sure if it actually failed if the `atob()` failes. We did get a success with what must be a malformed conversion?)

Its already set in the line above :) If atob fails it carries on with what is already set in `out`

**Review by jxmx — APPROVED** [review]

File: web/js/commands.js [hunk 1]
```diff
@@ -24,7 +24,10 @@ async function sendCommand(node, cmdStr) {
 	let cmdout = await postAPIForm("master/cmd", cmdForm);
 	let res = "";
 	if( cmdout["SUCCESS"] ){
-		let out = atob(cmdout["SUCCESS"]);
+		let out = cmdout['SUCCESS'];
```
Comment (Allan-N) [inline web/js/commands.js:27]: I know this change has already been merged but I don't get the two `out =` assignments.  Won't the second completely replace the first?

Comment (Pross) [reply web/js/commands.js:27]: > I know this change has already been merged but I don't get the two `out =` assignments. Won't the second completely replace the first?

It will if the data is base64 enoded,if it isnt then the first value is used. atob fails rather dramatically with an uncaught exception if the string is not base64 encoded,so its wrapped in a catch

Comment (Allan-N) [reply web/js/commands.js:27]: Ummm...  Here's what got merged :
```
        let out = cmdout['SUCCESS'];
        try {
            out = atob(cmdout["SUCCESS"]);
        } catch(e) {}
```

Comment (Pross) [reply web/js/commands.js:27]: `let out = cmdout['SUCCESS'];` we set out to whatever `cmdout['SUCCESS'];` is, its either a base64 or a string

now we do a try and catch on `cmdout['SUCCESS'];` so if it is encoded out becomes the decoded string and if it isnt we already set it anyway.

Is there a better solution?

Comment (Allan-N) [reply web/js/commands.js:27]: The [python] question is what happens to `out` if the `atob()` results in an exception?  If `out` is left with the prior value then you get the desired result.  But, if it works, then you've assigned the variable twice.  Could you have set `out = cmdout['SUCCESS']` in the exception handler?

Comment (Allan-N) [reply web/js/commands.js:27]: and, reading your reply a 2nd time, you are saying that the first assignment will be used if the `atob()` fails.  Sounds like the code works and it was just the double-assignment that caught my eye.

Comment (Pross) [reply web/js/commands.js:27]: let and try are two block scopes, so the access is different is my understanding of it.
